# Generated by Django 3.2.5 on 2021-08-05 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('prim_atendimento', 'Primeiro Atendimento'), ('atendimento', 'Atendimento'), ('fechamento', 'Fechamento'), ('entrega', 'Entrega')], max_length=16)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('concluido', 'Concluido')], default='pendente', max_length=9)),
                ('hr_criacao', models.DateTimeField(auto_now_add=True)),
                ('hr_atendimento', models.DateTimeField(blank=True, null=True)),
                ('garcom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('mesa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurante.mesa')),
            ],
        ),
    ]
