# Generated by Django 3.2.5 on 2021-08-12 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0001_initial'),
        ('garcom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='restaurante.itempedido')),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garcom.tarefa')),
            ],
        ),
    ]
